apiVersion: apps/v1
kind: Deployment
metadata:
  name: plastids-deploy
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      containers:
        - name: plastids
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-default-conf-uat
              readOnly: true
      volumes:
        - name: nginx-default-conf-uat
          configMap:
            defaultMode: 420
            name: nginx-default-conf-uat
